# Generated by Django 5.1.4 on 2024-12-13 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RobotModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=2, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "models",
            },
        ),
        migrations.RemoveField(
            model_name="robot",
            name="model",
        ),
        migrations.AlterField(
            model_name="robot",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterModelTable(
            name="robot",
            table="robots",
        ),
        migrations.CreateModel(
            name="RobotVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=2)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="robots.robotmodel",
                    ),
                ),
            ],
            options={
                "db_table": "versions",
                "unique_together": {("model", "version")},
            },
        ),
        migrations.AlterField(
            model_name="robot",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="robots",
                to="robots.robotversion",
            ),
        ),
    ]
