# Generated by Django 5.1.4 on 2024-12-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robots", "0002_robotmodel_remove_robot_model_alter_robot_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="robot",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
